[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    adafruit/Adafruit MAX31855 library
    knolleary/PubSubClient
    bblanchon/ArduinoJson@^6
    br3ttb/Arduino-PID-Library

[env:native]
platform = native
test_build_src = no
build_flags =
    -std=c++14
    -I test/mocks
    -I .
    -DUNIT_TEST
build_type = test
lib_deps =
    bblanchon/ArduinoJson@^6
