[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
build_src_filter = +<*> -<test/>
lib_deps =
    adafruit/Adafruit MAX31855 library
    knolleary/PubSubClient
    bblanchon/ArduinoJson@^6
    br3ttb/PID

[env:native]
platform = native
test_build_src = yes
build_src_filter = +<config.cpp>
build_flags =
    -std=c++14
    -I test/mocks
    -I .
    -DUNIT_TEST
build_type = test
lib_deps =
    bblanchon/ArduinoJson@^6
